M48
; DRILL file {KiCad 8.0.0} date 2024-03-17T16:56:20+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-17T16:56:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0402
%
G90
G05
T1
X4.7008Y-4.0201
X4.7008Y-4.2476
T2
X4.7208Y-3.0262
X4.7208Y-3.3402
T3
X1.1598Y-3.4803
X1.1598Y-4.7795
M30
