M48
; DRILL file {KiCad 8.0.1} date 2024-03-19T22:33:07+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-19T22:33:07+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.020
%
G90
G05
T1
X119.4Y-102.11
X119.4Y-107.89
T2
X119.909Y-76.864
X119.909Y-84.84
T3
X29.46Y-88.4
X29.46Y-121.4
M30
