name: markdown-autodocs
permissions: write-all
on: [push]

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.2
        with:
          output_file_paths: '[./docs/*]'
